spring:
  application:
    name: trace
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来）,值越大收集越及时
server:
  port: 8989
logging:
  file:
    path: ${user.dir}/${spring.application.name}/
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'