server:
  port: 8989

spring:
  application:
    name: trace

management:
  server:
    # 指定监端点暴露监听端口
    port: 10101
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: http://10.188.188.170:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 #采样率默认为0.1(0.1就是10次只能有一次被记录下来）,值越大收集越及时
  endpoints:
    #配置不同类型(web)
    web:
      cors:
        #允许跨域的方法
        allowed-methods: *
      # 配置http方式暴露端点
      exposure:
        #配置暴露的端点,配置"*"暴露全部
        include: "*"
        #配置不暴露的端点
        exclude:
      # 配置通过http方式暴露端点的根路径
      base-path: "/actuator"
logging:
  file:
    path: ${user.dir}/${spring.application.name}/
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  # config: # Location fo logging configuration
